version: "3.7"

services:
  db:
    image: keinos/sqlite3:latest
  web:
    restart: always
    build: ./vehicles/
    command: python manage.py migrate & python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/vehicles
    ports:
      - "8000:8000"
    depends_on:
      - db